/*
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef LIBNFC_TF_LOCAL_H
#define LIBNFC_TF_LOCAL_H

#include <sys/types.h>
#include <openssl/aes.h>

enum {
	NFC_HW_INIT = 0,

	NFC_HW_CLOSED,

	NFC_HW_PRIMARY_SETTING,
	NFC_HW_RECOGNIZING,
	NFC_HW_LOADING,

	NFC_HW_IDLING,
	
	NFC_HW_IDLING_POLLING,
	NFC_HW_IDLING_TAG_PROCESSING,
	NFC_HW_HOLDING,
	NFC_HW_HANDLED,
	
	NFC_HW_STATUS_MAX,
};

/* T,F. header */
#define NFC_TF_CMD_HEADER_SEND			0x40
#define NFC_TF_CMD_HEADER_RESULT		0x50
#define NFC_TF_CMD_HEADER_NACK			0xfe

/* T.F. command */
#define NFC_TF_CMD_COM_OPEN				0x12
#define NFC_TF_CMD_COM_CLOSE			0x13
#define NFC_TF_CMD_COM_QUERYSTATE		0x14
#define NFC_TF_CMD_COM_GETINFORMATION	0x15
#define NFC_TF_CMD_COM_DIAGNOSE			0x16
#define NFC_TF_CMD_COM_RECOVER			0x18
#define NFC_TF_CMD_COM_PRIMARYKEY		0x19
#define NFC_TF_CMD_COM_SETPRIMARYKEY	0x1a
#define NFC_TF_CMD_COM_LOADING			0x22
#define NFC_TF_CMD_COM_DOWNLOAD			0x23
#define NFC_TF_CMD_COM_DOWNLOAD_ENC		0x24
#define NFC_TF_CMD_COM_UPLOAD			0x25
#define NFC_TF_CMD_COM_UPLOAD_ENC		0x26
#define NFC_TF_CMD_COM_COMPLETE_LOAD	0x28
#define NFC_TF_CMD_COM_CONTROL_LED		0x30
#define NFC_TF_CMD_COM_FINDMEDIA		0x40
#define NFC_TF_CMD_COM_FREEMEDIA		0x41
#define NFC_TF_CMD_COM_OPENMEDIA		0x48
#define NFC_TF_CMD_COM_CLOSEMEDIA		0x49
#define NFC_TF_CMD_COM_THROUGH			0x4a

#define NFC_TF_CMD_COM_ENABLE_RECOGNITION	0x52
#define NFC_TF_CMD_COM_DISABLE_RECOGNITION	0x53
#define NFC_TF_CMD_COM_OPEN_RECOGNITION		0x56
#define NFC_TF_CMD_COM_OPENSECURE_RECOGNITION	0x57
#define NFC_TF_CMD_COM_REQUEST_RECOGNITION	0x58

#define NFC_TF_CMD_COM_WRITE_FELICA_ENC		0x68
#define NFC_TF_CMD_COM_READ_FELICA_ENC		0x69
#define NFC_TF_CMD_COM_AUTHENTICATE_FELICA	0x62
#define NFC_TF_CMD_COM_WRITE_FELICA			0x63
#define NFC_TF_CMD_COM_READ_FELICA			0x64

#define NFC_TF_CMD_COM_WRITE_MIFARE_PAGE	0x72
#define NFC_TF_CMD_COM_READ_MIFARE_PAGE		0x73
#define NFC_TF_CMD_COM_WRITE_MIFARE_BLOCK	0x74
#define NFC_TF_CMD_COM_READ_MIFARE_BLOCK	0x75

#define NFC_TF_CMD_COM_SELECT_JICSAP_FILE	0x82
#define NFC_TF_CMD_COM_VERIFY_JICSAP		0x83
#define NFC_TF_CMD_COM_GET_JICSAP_CHALLENGE	0x85
#define NFC_TF_CMD_COM_AUTHENTICATE_JICSAP	0x86
#define NFC_TF_CMD_COM_UPDATE_JICSAP		0x88
#define NFC_TF_CMD_COM_APPEND_JICSAP_RECORD	0x8a
#define NFC_TF_CMD_COM_READ_JICSAP			0x89
#define NFC_TF_CMD_COM_ERASE_JICSAP_ALL		0x8b
#define NFC_TF_CMD_COM_PUT_JICSAP_DATA		0x8c
#define NFC_TF_CMD_COM_GET_JICSAP_DATA		0x8d

#define NFC_TF_CMD_COM_PUT_NDEF_MESSAGE		0x92
#define NFC_TF_CMD_COM_GET_NDEF_MESSAGE		0x93

#define NFC_TF_CMD_COM_WRITE_ICODESLI		0xa2
#define NFC_TF_CMD_COM_READ_ICODESLI		0xa3

#define NFC_TF_CMD_COM_CREATE_LLCPSAP		0xb2
#define NFC_TF_CMD_COM_DESTROY_LLCPSAP		0xb3
#define NFC_TF_CMD_COM_LISTEN_LLCP			0xb4
#define NFC_TF_CMD_COM_CONNECT_LLCP			0xb5
#define NFC_TF_CMD_COM_ACCEPT_LLCP			0xb6
#define NFC_TF_CMD_COM_GET_LLCPSAPINFO		0xb7
#define NFC_TF_CMD_COM_WRITE_LLCP			0xb8
#define NFC_TF_CMD_COM_READ_LLCP			0xb9

/* T.F. result */
#define NFC_TF_CMD_RESULT_SUCCEEDED		0x00
#define NFC_TF_CMD_RESULT_LLCP_CONNECTING	0x20
#define NFC_TF_CMD_RESULT_FAILED_RECOGNITION	0xcc
#define NFC_TF_CMD_RESULT_FAILED_ENC		0xfb

/* T.F. QueryState Result */
/* doc rev 0.05 */
#define NFC_TF_QUERYSTATE_CLOSED                0x05
#define NFC_TF_QUERYSTATE_IDLING                0x06
#define NFC_TF_QUERYSTATE_PRIMARY               0x07
#define NFC_TF_QUERYSTATE_RECOGNIZING   	0x08
#define NFC_TF_QUERYSTATE_LOADING               0x09
#define NFC_TF_QUERYSTATE_HOLDING               0x0a
#define NFC_TF_QUERYSTATE_HANDLED               0x0b
#define NFC_TF_QUERYSTATE_ERR                   0xff

/* T.F. FindMedia Result MEDIAS */
#define NFC_TF_MEDIAS_RF_FELICA			0x01
#define NFC_TF_MEDIAS_RF_ISO14443A		0x02
#define NFC_TF_MEDIAS_RF_ISO14443B		0x04
#define NFC_TF_MEDIAS_RF_ISO15693		0x08
#define NFC_TF_MEDIAS_RF_P2PINITIATOR	0x10

#define NFC_TF_MEDIAS_MEDIA_OTHER		0x00
#define NFC_TF_MEDIAS_MEDIA_FELICA		0x01
#define NFC_TF_MEDIAS_MEDIA_MOBILE_FELICA	0x02
#define NFC_TF_MEDIAS_MEDIA_MIFARE		0x03
#define NFC_TF_MEDIAS_MEDIA_JICSAP		0x04
#define NFC_TF_MEDIAS_MEDIA_NDEF		0x05
#define NFC_TF_MEDIAS_MEDIA_ICODESLI	0x06
#define NFC_TF_MEDIAS_MEDIA_P2PTARGET	0x07

#define NFC_TF_CMD_HEADER_BYTE		1
#define NFC_TF_CMD_COMMAND_BYTE		1
#define NFC_TF_CMD_PARAM_LEN_BYTE	2
// RICOH ADD-S Felica Security Access
#define NFC_TF_CMD_RESULT_BYTE		1
#define NFC_TF_CMD_BCC_BYTE			1
#define NFC_TF_CMD_PARAM_MAX_LEN	496

#define NFC_TF_READ_TRY_WAIT		10 * 1000
#define NFC_TF_READ_TRY_TIME_OUT	100
// RICOH ADD-E Felica Security Access

// RICOH ADD-S NDEF Detection Settings
/* FindMedia Request FELICA */
#define NFC_TF_FINDMEDIA_PARAM_FELICA_BIT_NDEF_DETECTION_DISABLE	0x08  // 3bit

/* FindMedia Request 14443A */
#define NFC_TF_FINDMEDIA_PARAM_14443A_BIT_NDEF_DETECTION_DISABLE	0x08  // 3bit

/* FindMedia Request 14443B */
#define NFC_TF_FINDMEDIA_PARAM_14443B_BIT_NDEF_DETECTION_DISABLE	0x08  // 3bit
// RICOH ADD-E NDEF Detection Settings


#define NFC_TF_CMD_HEADER_LENGTH	(NFC_TF_CMD_HEADER_BYTE + NFC_TF_CMD_COMMAND_BYTE + NFC_TF_CMD_PARAM_LEN_BYTE)

enum {
	NFC_TF_LLCP_SOCK_TYPE_NONE = 0,
	NFC_TF_LLCP_SOCK_TYPE_CLIENT,
	NFC_TF_LLCP_SOCK_TYPE_SERVER,
	NFC_TF_LLCP_SOCK_TYPE_SERVER_ACCEPT,
};

enum {
	NFC_TF_LLCP_SOCK_STAT_NONE = 0,
	NFC_TF_LLCP_SOCK_STAT_CREATE,
	NFC_TF_LLCP_SOCK_STAT_ACCEPT,
	NFC_TF_LLCP_SOCK_STAT_CONNECTING,
	NFC_TF_LLCP_SOCK_STAT_ESTABLISH,
};

enum {
	NFC_TF_GET_INFO_ERR_PROTOCOL_NOT_SUPPORTED = 1,
	NFC_TF_GET_INFO_ERR_OPENMEDIA,
	NFC_TF_GET_INFO_ERR_ILLEGAL_PARAM_LENGTH,
	NFC_TF_GET_INFO_ERR_RESET_TO_READY,
	NFC_TF_GET_INFO_ERR_SET_INVENTORY,
	NFC_TF_GET_INFO_ERR_CLOSEMEDIA,
	NFC_TF_GET_INFO_ERR_MEDIA_NOT_SUPPORTED,
};

#define NFC_TF_LLCP_MIU_DEFAULT		128
#define NFC_TF_LLCP_RW_DEFAULT		1
#define NFC_TF_LLCP_WKS_DEFAULT		1
#define NFC_TF_LLCP_LTO_DEFAULT		10
#define NFC_TF_LLCP_OPTION_DEFAULT	0
#define NFC_TF_LLCP_MIUX_DEFAULT	0

#define NFC_TF_LLCP_DATA_MAX_LENGTH	493


#define NFC_TF_NDEF_FLAG_MB		(1 << 7)	/* Message Begin */
#define NFC_TF_NDEF_FLAG_ME		(1 << 6)	/* Message End */
#define NFC_TF_NDEF_FLAG_CF		(1 << 5)	/* Chunk Flag */
#define NFC_TF_NDEF_FLAG_SR		(1 << 4)	/* Short Record */
#define NFC_TF_NDEF_FLAG_IL		(1 << 3)	/* ID_LENGTH field is present */

#define NFC_TF_NDEF_TNF_EMPTY		0x0
#define NFC_TF_NDEF_TNF_WELL_KNOWN	0x1
#define NFC_TF_NDEF_TNF_MEDIA_TYPE	0x2
#define NFC_TF_NDEF_TNF_URI		0x3
#define NFC_TF_NDEF_TNF_EXTERNAL_TYPE	0x4
#define NFC_TF_NDEF_TNF_UNKNOWN		0x5
#define NFC_TF_NDEF_TNF_UNCHANGED	0x6
#define NFC_TF_NDEF_TNF_RESERVED	0x7
#define NFC_TF_NDEF_TNF_MASK		0x07

// RICOH ADD-S Felica Security Access
/** data params**/
/* command code (FeliCa Card Command) */
#define FELICA_CMD_READ_FELICA_ENC					0x06
#define FELICA_RES_READ_FELICA_ENC					0x07
#define FELICA_CMD_WRITE_FELICA_ENC					0x08
#define FELICA_RES_WRITE_FELICA_ENC					0x09
#define FELICA_CMD_AUTHENTICATE_FELICA				0x10
#define FELICA_RES_AUTHENTICATE_FELICA				0x11
#define FELICA_CMD_READ_FELICA						0x14
#define FELICA_RES_READ_FELICA						0x15
#define FELICA_CMD_WRITE_FELICA						0x16
#define FELICA_RES_WRITE_FELICA						0x17

/* result code (FeliCa Data Access Command Set) */
#define NFC_TF_RESULT_SUCCEEDED						0x00
#define NFC_TF_RESULT_ERR_PARAM						0xfd
#define NFC_TF_RESULT_ERR_ILLEGAL_HANDLE			0xfc
#define NFC_TF_RESULT_TIMEOUT_MEDIA_COMMUNICATION	0xd5
#define NFC_TF_RESULT_ILLEGAL_RESPONSE_FROM_MEDIA	0xd4
#define NFC_TF_RESULT_ILLEGAL_MEDIA_STATUS			0xd3
#define NFC_TF_RESULT_FAILED_KEY_GENERATION			0xcd
#define NFC_TF_RESULT_FAILED_ENCRYPTION				0xce
#define NFC_TF_RESULT_ABNORMAL_HANDLE				0xde
#define NFC_TF_RESULT_ERR_EXECTION					0xdf

/* group key, user key */
#define NFC_TF_GROUP_KEY_USAGE_KEY_INDEX			0x01
#define NFC_TF_GROUP_KEY_USAGE_KEY_DIRECTLY			0x80
#define NFC_TF_GROUP_KEY_ATTRIBUTE_KEY_DIRECTLY		0x00
#define NFC_TF_USER_KEY_USAGE_KEY_INDEX				0x01
#define NFC_TF_USER_KEY_USAGE_KEY_DIRECTLY			0x80
#define NFC_TF_USER_KEY_ATTRIBUTE_KEY_DIRECTLY		0x00

/* system code */
#define  NFC_TF_SYSTEM_CODE_INITIAL					0x00
#define  NFC_TF_SYSTEM_CODE_WILD_CARD				0xff
#define  NFC_TF_SYSTEM_CODE_ENABLE					0x04


/** array number **/
/* from NFC Service */
#define NFC_TF_LENGTH_REQ_ARRAY_NUMBER						0
#define NFC_TF_COMMAND_CODE_REQ_ARRAY_NUMBER				1

#define NFC_TF_READ_ENC_SERVICE_CODE_REQ_ARRAY_NUMBER		2
#define NFC_TF_READ_ENC_BLOCK_TYPE_REQ_ARRAY_NUMBER			4
#define NFC_TF_READ_ENC_BLOCK_NUMBER_REQ_ARRAY_NUMBER		5
#define NFC_TF_READ_ENC_BLOCK_COUNT_REQ_ARRAY_NUMBER		7

#define NFC_TF_AUTH_AREA_COUNT_REQ_ARRAY_NUMBER				2
#define NFC_TF_AUTH_AREA_LIST_REQ_ARRAY_NUMBER				3
#define NFC_TF_AUTH_SERVICE_COUNT_REQ_ARRAY_NUMBER			19
#define NFC_TF_AUTH_SERVICE_LIST_REQ_ARRAY_NUMBER			20
#define NFC_TF_AUTH_GROUP_KEY_REQ_ARRAY_NUMBER				36
#define NFC_TF_AUTH_USER_KEY_REQ_ARRAY_NUMBER				52

#define NFC_TF_READ_BLOCK_TYPE_REQ_ARRAY_NUMBER				2
#define NFC_TF_READ_BLOCK_NUMBER_REQ_ARRAY_NUMBER			3
#define NFC_TF_READ_BLOCK_COUNT_REQ_ARRAY_NUMBER			5

/* from ToppanR/W */
#define NFC_TF_RESULT_RES_ARRAY_NUMBER						1
#define NFC_TF_LENGTH_RES_ARRAY_NUMBER						2

#define NFC_TF_READ_MEDIA_STATUS_1_RES_ARRAY_NUMBER			4
#define NFC_TF_READ_MEDIA_STATUS_2_RES_ARRAY_NUMBER			5
#define NFC_TF_READ_DATA_RES_ARRAY_NUMBER					6

#define NFC_TF_DEVICE_CODE_RES_ARRAY_NUMBER					4
#define NFC_TF_DEVICE_VERSION_RES_ARRAY_NUMBER				20
#define NFC_TF_DEVICE_SERIAL_RES_ARRAY_NUMBER				30
#define NFC_TF_FIRM_ID_RES_ARRAY_NUMBER						42
#define NFC_TF_FIRM_VERSION_RES_ARRAY_NUMBER				50


/** data length **/
/* header, result, length */
#define NFC_TF_HEADER_LENGTH						1
#define NFC_TF_COMMAND_LENGTH						1
#define NFC_TF_RESULT_LENGTH						1
#define NFC_TF_LENGTH_LENGTH						2

/* Params Field */
#define NFC_TF_HANDLE_NUMBER_LENGTH					2
#define NFC_TF_SERVICE_CODE_LENGTH					2
#define NFC_TF_BLOCK_TYPE_LENGTH					1
#define NFC_TF_BLOCK_NUMBER_LENGTH					2
#define NFC_TF_BLOCK_COUNT_LENGTH					1
#define NFC_TF_AREA_COUNT_LENGTH					1
#define NFC_TF_AREA_LIST_LENGTH						16
#define NFC_TF_SERIVCE_COUNT_LENGTH					1
#define NFC_TF_SERVICE_LIST_LENGTH					16
#define NFC_TF_GROUP_KEY_USAGE_LENGTH				1
#define NFC_TF_GROUP_KEY_ATTRIBUTE_LENGTH			1
#define NFC_TF_GROUP_KEY_LENGTH						16
#define NFC_TF_USER_KEY_USAGE_LENGTH				1
#define NFC_TF_USER_KEY_ATTRIBUTE_LENGTH			1
#define NFC_TF_USER_KEY_LENGTH						16

#define NFC_TF_MRDIA_STATUS1_LENGTH					1
#define NFC_TF_MRDIA_STATUS2_LENGTH					1

#define NFC_TF_READ_FELICA_ENC_SEND_PARAM_LENGTH	0x07
#define NFC_TF_AUTH_FELICA_SEND_PARAM_LENGTH		0x47
#define NFC_TF_READ_FELICA_SEND_PARAM_LENGTH		0x05

#define NFC_TF_SYSTEM_CODE_LENGTH					2

#define NFC_TF_DEVICE_CODE_LENGTH					16
#define NFC_TF_DEVICE_VERSION_LENGTH				10
#define NFC_TF_DEVICE_SERIAL_LENGTH					12
#define NFC_TF_FIRM_ID_LENGTH						8
#define NFC_TF_FIRM_VERSION_LENGTH					8
// RICOH ADD-E Felica Security Access

#endif


